[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "esis-instrument-paper"
authors = [
    {name = "Roy T. Smart", email = "roytsmart@gmail.com"},
]
description = "An AAS journal article describing the EUV Snapshot Imaging Spectrograph (ESIS) sounding rocket instrument."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "pylatex",
    "aastex>=0.4.0",
    "num2words",
    "euv-snapshot-imaging-spectrograph>=1.0.0",
]
dynamic = ["version"]

[project.optional-dependencies]
test = [
    "pytest",
]
doc = [
    "pytest",
    "matplotlib",
    "graphviz",
    "sphinx-autodoc-typehints",
    "pydata-sphinx-theme",
    "ipykernel",
    "sphinx-favicon",
]

[project.urls]
Homepage = "https://github.com/esis-mission/esis-instrument-paper"

[tool.setuptools.packages.find]
include = ["esis_instrument_paper*"]

[tool.setuptools.package-data]
esis_instrument_paper = ["*.cls", "*.bst", "*.bib", "*.png"]

[tool.setuptools_scm]
